### ISSUE TITLE
긴 코드 응답이 왔을 경우 화면을 넘어가는 문제

### ISSUE THREAD

**Issue by JuhyuckHong** [Team2clone/team2CloneFE#22]
![image](https://github.com/Team2clone/team2CloneFE/assets/128202933/319f9c40-3ad3-4045-aa18-fa54cc467f92)

고정된 폭을 가지면서 가로 스크롤이 생기도록 개선이 필요해 보입니다.

**Comment by night-hawks-wake** [comment]
Main 컴포넌트의 레이아웃을 수정하면서 함께 수정되었습니다. 감사합니다!

![CleanShot 2023-06-05 at 14 28 26@2x](https://github.com/Team2clone/team2CloneFE/assets/127172647/cc2f5790-73ad-4a11-87b7-da3c2c3274f6)
